name: 'qa-e2e'
description: 'Run mycs qa e2e tests'
inputs:
  suite:
    description: 'test suite to run'
    required: true
    default: 'smoke'
  branch:
    description: 'branch to run the e2e test on'
    required: true
  token:
    description: circleci token
    required: true
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/runQA.sh
      shell: bash
      env:
        RUN_SUITES: ${{ inputs.suite }}
        CIRCLE_BRANCH: ${{ inputs.branch }}
        QA_TOKEN: ${{ inputs.token }}
